### ISSUE TITLE
Xaeros minimap conflict?

### ISSUE THREAD

**Issue by tacogerbil** [user11681/limitless#24] opened 2020-11-04 00:01 UTC
This mod for some reason makes my server reject [xaeros-minimap](https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap) , rejecting it as not being a server side mod.  
I literally only have This mod, Xaeros and fabric-api-0.25.1+build.416-1.16.  I'm on Fabric 1,16.4 now but was was also happening on 1.16.3.. EXACTLY the same.  If I remove this mod Xaeros runs just fine.
[15:51:09] [main/WARN]: Error loading class: net/minecraft/class_437 (java.lang.ClassNotFoundException: net/minecraft/class_437)
[15:51:09] [main/FATAL]: Failed to start the minecraft server
net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'server' provided by 'xaerominimap'
at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:193) ~[fabric-1.16.4_0.10.6B214.jar:?]
at net.fabricmc.loader.FabricLoader.getEntrypointContainers(FabricLoader.java:272) ~[fabric-1.16.4_0.10.6B214.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:44) ~[fabric-1.16.4_0.10.6B214.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-1.16.4_0.10.6B214.jar:?]
at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-1.16.4_0.10.6B214.jar:?]
at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224) [fabric-1.16.4_0.10.6B214.jar:?]
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141) [fabric-1.16.4_0.10.6B214.jar:?]
at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric-1.16.4_0.10.6B214.jar:?]
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-1.16.4_0.10.6B214.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-1.16.4_0.10.6B214.jar:?]
at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-1.16.4_0.10.6B214.jar:?]
Caused by: java.lang.NullPointerException
at org.spongepowered.asm.mixin.transformer.ClassInfo.getCommonSuperClass(ClassInfo.java:2041) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.spongepowered.asm.mixin.transformer.ClassInfo.getCommonSuperClass(ClassInfo.java:1993) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.spongepowered.asm.mixin.transformer.ClassInfo.getCommonSuperClass(ClassInfo.java:1965) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.spongepowered.asm.transformers.MixinClassWriter.getCommonSuperClass(MixinClassWriter.java:51) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.objectweb.asm.SymbolTable.addMergedType(SymbolTable.java:1202) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.objectweb.asm.Frame.merge(Frame.java:1299) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.objectweb.asm.Frame.merge(Frame.java:1244) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:769) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:649) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:452) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.spongepowered.asm.transformers.TreeTransformer.writeClass(TreeTransformer.java:82) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.spongepowered.asm.mixin.transformer.HackedMixinTransformer.transform(HackedMixinTransformer.java:49) ~[f6740e1b-9119-4d77-8cf3-f7bba022038d.jar:?]
at org.spongepowered.asm.mixin.transformer.HackedMixinTransformer.transformClass(HackedMixinTransformer.java:27) ~[f6740e1b-9119-4d77-8cf3-f7bba022038d.jar:?]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:178) ~[fabric-1.16.4_0.10.6B214.jar:?]
at org.spongepowered.asm.mixin.transformer.HackedMixinTransformer.transformClassBytes(HackedMixinTransformer.java:12) ~[f6740e1b-9119-4d77-8cf3-f7bba022038d.jar:?]
at org.spongepowered.asm.mixin.transformer.FabricMixinTransformerProxy.transformClassBytes(FabricMixinTransformerProxy.java:23) ~[fabric-1.16.4_0.10.6B214.jar:?]
at net.fabricmc.loader.launch.knot.EarlyKnotClassDelegate.getPostMixinClassByteArray(EarlyKnotClassDelegate.java:111) ~[f6740e1b-9119-4d77-8cf3-f7bba022038d.jar:?]
at net.fabricmc.loader.launch.knot.UnsafeKnotClassLoader.loadClass(UnsafeKnotClassLoader.java:69) ~[f6740e1b-9119-4d77-8cf3-f7bba022038d.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_131]
at java.lang.Class.forName0(Native Method) ~[?:1.8.0_131]
at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_131]
at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45) ~[fabric-1.16.4_0.10.6B214.jar:?]
at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:114) ~[fabric-1.16.4_0.10.6B214.jar:?]
at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:101) ~[fabric-1.16.4_0.10.6B214.jar:?]
at net.fabricmc.loader.EntrypointStorage.getEntrypointContainers(EntrypointStorage.java:186) ~[fabric-1.16.4_0.10.6B214.jar:?]
... 19 more

**Comment by user11681** [comment] 2020-11-04 00:07
duplicate of #14

**Closed** 2020-11-09 10:45 UTC
Labels: bug, duplicate
